name:                ch-challenge
version:             0.1.0.0
github:              "githubuser/ch-challenge"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/ch-challenge#readme>

dependencies:
- base >= 4.7 && < 5
- text

library:
  source-dirs: src
  dependencies:
    - aeson
    - bytestring
    - unordered-containers

executables:
  ch-challenge-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ch-challenge
    - text
    - aeson
    - bytestring
    - unordered-containers >= 0.2.7 && < 0.3
    - hashmap
    default-extensions:
    - OverloadedStrings
    - DeriveGeneric

tests:
  ch-challenge-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ch-challenge
    - text
    default-extensions:
    - OverloadedStrings
